function A = crossfilt(A)
[m,n] = size(A);
ic = 2:m-1; % Centre rows
jc = 2:n-1; % Centre columns
ib = [1 m]; % Border rows
jb = [1 n]; % Border columns
B = NaN(m,n,5);
B(:,:,1) = A; % Centre
B(ic,:,2) = A(1:m-2,:); % North
B(ic,:,3) = A(3:m,:); % South
B(:,jc,4) = A(:,1:n-2); % West
B(:,jc,5) = A(:,3:n); % East
B(m,jb,2) = A(m-1,jb); % North of corners
B(1,jb,3) = A(2,jb); % South of corners
B(ib,n,4) = A(ib,n-1); % West of corners
B(ib,1,5) = A(ib,2); % East of corners
B = sort(B,3);
A(ic,jc) = B(ic,jc,3); % Centre
A(ib,jc) = B(ib,jc,2); % North and south
A(ic,jb) = B(ic,jb,2); % West and east
A(ib,jb) = B(ib,jb,2); % Corners